DROP database IF EXISTS DB_LOCATION 
create database DB_LOCATION;

go

use DB_LOCATION;
go

create table LOCATION(
	ID_LOCATION integer not null primary key identity,
	FK_ID_OBJECT integer not null,
	LATITUDE float,
	LONGITUDE float,
	TIME_START DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	TIME_END DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (TIME_START, TIME_END)
)WITH (SYSTEM_VERSIONING = ON);

GO

create table OBJECT(
	ID_OBJECT integer not null primary key identity,
	NAME VARCHAR(40)
)

GO

ALTER TABLE LOCATION
ADD
CONSTRAINT FK_ID_OBJECT FOREIGN KEY (FK_ID_OBJECT) REFERENCES OBJECT (ID_OBJECT);
GO

insert into object (name) values ('Carro');
insert into object (name) values ('Bike');
insert into object (name) values ('Moto');

insert into location( FK_ID_OBJECT, LATITUDE, LONGITUDE) values (1,-29.696678,-53.817198);
--update LOCATION set LATITUDE = -29.684378, LONGITUDE = -53.814286 where ID_LOCATION = 1;
insert into location( FK_ID_OBJECT, LATITUDE, LONGITUDE) values (2,-29.684378,-53.814286);
insert into location( FK_ID_OBJECT, LATITUDE, LONGITUDE) values (3,-29.682013,-53.802943);

select * from LOCATION
for system_time
between '2000-01-01 00:00:00.0000000' and '2022-01-01 00:00:00.0000000'

--LIST ALL OBJECTS
select O.ID_OBJECT AS ID_OBJECT, o.name as NAME_OBJECT, l.LATITUDE AS LATITUDE, l.LONGITUDE AS LONGITUDE
from LOCATION l
join OBJECT o on o.ID_OBJECT = l.FK_ID_OBJECT


--LIST HISTORY BY ID OBJECT
select O.NAME AS NAME_OBJECT, LOCATION.LATITUDE AS LATITUDE, LOCATION.LONGITUDE AS LONGITUDE, LOCATION.TIME_START AS TIME_START,LOCATION.TIME_END AS TIME_END 
from LOCATION
for system_time
between '2000-01-01 00:00:00.0000000' and '2022-01-01 00:00:00.0000000'
JOIN OBJECT O ON O.ID_OBJECT = LOCATION.FK_ID_OBJECT
where ID_LOCATION = 1